"""LLM 分析层出口（Phase 2）。"""

from app.llm.json_extraction import (
    REPAIR_EXTRACTED_OBJECT,
    REPAIR_INSERTED_COMMAS,
    REPAIR_PYTHON_LITERALS,
    REPAIR_QUOTED_BARE_KEYS,
    REPAIR_STRIPPED_BOM,
    REPAIR_STRIPPED_FENCE,
    REPAIR_TRAILING_COMMAS,
    ExtractionResult,
    JSONExtractionError,
    extract_json,
    find_balanced_json,
)
from app.llm.prompts import (
    ANALYSIS_PROMPT_VERSION,
    FORBIDDEN_RESPONSE_KEYS,
    RESPONSE_JSON_SCHEMA,
    SYNTHESIS_PROMPT_VERSION,
    Prompt,
    build_analysis_prompt,
    build_retry_hint,
    build_synthesis_prompt,
)
from app.llm.service import (
    DEFAULT_MAX_ATTEMPTS,
    STEP_EXTRACTION,
    STEP_TRANSPORT,
    STEP_VALIDATION,
    AnalysisOutcome,
    AttemptRecord,
    LLMAnalysisService,
    summarize_validation_error,
)

__all__ = [
    "LLMAnalysisService",
    "AnalysisOutcome",
    "AttemptRecord",
    "STEP_TRANSPORT",
    "STEP_EXTRACTION",
    "STEP_VALIDATION",
    "DEFAULT_MAX_ATTEMPTS",
    "summarize_validation_error",
    "extract_json",
    "find_balanced_json",
    "ExtractionResult",
    "JSONExtractionError",
    "REPAIR_STRIPPED_FENCE",
    "REPAIR_EXTRACTED_OBJECT",
    "REPAIR_QUOTED_BARE_KEYS",
    "REPAIR_INSERTED_COMMAS",
    "REPAIR_TRAILING_COMMAS",
    "REPAIR_PYTHON_LITERALS",
    "REPAIR_STRIPPED_BOM",
    "ANALYSIS_PROMPT_VERSION",
    "SYNTHESIS_PROMPT_VERSION",
    "RESPONSE_JSON_SCHEMA",
    "FORBIDDEN_RESPONSE_KEYS",
    "Prompt",
    "build_analysis_prompt",
    "build_synthesis_prompt",
    "build_retry_hint",
]
